import { StyleSheet } from "react-native";

import { colors } from "constants";
import { deviceWidth } from "../../utils";

export default StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 24,
    flex: 1,
  },
  logoWrapper: {
    width: "100%",
    height: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  forgotPassword: {
    justifyContent: "center",
    alignItems: "flex-end",
    width: "100%",
  },
  bottomViewLogin: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    marginTop: 8,
  },
  loginBtn: {
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    position: "relative",
    top: 0,
    left: 0,
    minWidth: "100%",
    borderRadius: 4,
    marginTop: 32,
    maxWidth: deviceWidth - 32,
    height: 50,
    backgroundColor: colors.buttonPrimary,
  },
  buttonsWrapper: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    width: "100%",
    position: "absolute",
    bottom: 24,
    height: 117,
    paddingTop: 16,
    width: deviceWidth - 48,
    zIndex: 10,
  },
  submitBtn: {
    width: deviceWidth - 48,
    minWidth: deviceWidth - 48,
    alignSelf: "center",
  },
  formWrapper: {
    flex: 1,
    marginTop: 16,
  },
  textFieldWrapper: {
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    margin: 0,
    marginBottom: 16,
    padding: 0,
    width: deviceWidth - 48,
    borderColor: colors.gray,
    height: 44,
    borderBottomWidth: 1,
    borderColor: colors.gray,
    paddingHorizontal: 9,
  },
  textFieldWrapperWithoutBorder: {
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    margin: 0,
    marginBottom: 16,
    padding: 0,
    width: deviceWidth - 48,
    height: 44,
    borderColor: colors.gray,
  },
  input: {
    height: 44,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderColor: colors.gray,
    paddingVertical: 11,
    flex: 1,
    color: colors.fontPrimaryColor,
    width: deviceWidth - 48,
  },
  inputSecond: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderColor: colors.gray,
    flex: 1,
    color: colors.fontPrimaryColor,
    width: deviceWidth - 48,
    paddingLeft: 9,
  },
  iconWrapper: {
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  countryPickerWrapper: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderColor: colors.gray,
    width: "100%",
    paddingBottom: 11,
    paddingHorizontal: 9,
  },
});
